### ISSUE TITLE
Menuntaskan ERD

### ISSUE THREAD

**Issue by rafzarf** [rafzarf/ena-me-project#3]
### Task List Minggu 4, ERD:

- [ ] Perbaiki ERD sampai selesai.
- [ ] Pastikan semua kolom pada formulir fisik terwakili dengan baik di dalam database.
- [ ] Verifikasi bahwa semua kolom yang diperlukan dari formulir fisik sudah dimasukkan.
- [ ] Pastikan database lengkap untuk menghindari penyesuaian bolak-balik.
- [ ] Pastikan kekompletan untuk mengekspor PDF dengan tata letak yang identik dengan formulir fisik.

**Comment by rdhst** [comment]
tes
